# Template: grn_development
EXPERIMENT_NAME: grn_development_excitatory_postnatal
PSEUDOBULK_FILE: /home/rajd2/rds/rds-cam-psych-transc-Pb9UGUlrwWc/Cam_snRNAseq/integrated/VelWangPsychAD_100k_postnatal_chemistry/pseudobulk_output/by_cell_class.h5ad
CELL_CLASS_COL:   cell_class
CELL_CLASS_VALUE: Excitatory
CHILD_STARTS:  [1, 2, 3, 4, 5]
GAP_STARTS:    [8, 9, 10, 11, 12]
GAP_LENGTHS:   [1, 2, 3, 4, 5]
ADOL_ENDS:     [21, 22, 23, 24, 25]
