# Step5 notebook config for VELMESHEV-V3 retransform outputs
output_dir: /home/rajd2/rds/rds-cam-psych-transc-Pb9UGUlrwWc/Cam_snRNAseq/integrated/VelWangPsychAD_100k_postnatal_source-chemistry_tuning2_15k/retransform_velmeshev_v3
